### ISSUE TITLE
ctz fails with type: nodejs

### ISSUE THREAD

**Issue by Akatuoro** [SAP/ctz#24]
Running
```
cds init bookshop-k8s --add tiny-sample,hana,xsuaa,helm,containerize
```

produces a ctz module
```
  - name: bookshop-k8s-srv
    build-parameters:
      buildpack:
        type: nodejs
        builder: builder-jammy-base
        path: gen/srv
        env:
          BP_NODE_RUN_SCRIPTS: ""
```

When running `ctz containerize.yaml`, building this module fails with

```
Containerising module bookshop-k8s-srv...
ERROR: failed to build: failed to fetch base layers: saving image with ID "sha256:3274fe28594f484240fc3f17e46b7b45e304830e544dcdd82ce19472d159ef71" from the docker daemon: Error response from daemon: unable to create manifests file: NotFound: content digest sha256:70a3727d92007b1b4d739ebf0060c0f455dca3a95ddd51835fd8331150d2dcb0: not found
```

Running `pack` with `--buildpack gcr.io/paketo-buildpacks/nodejs` manually also fails with the same error. Changing it to `--buildpack paketo-buildpacks/nodejs` works.
